# Generated by Django 5.2.17 on 2026-09-22 15:20

import catalog.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('vocals_file', models.FileField(blank=True, null=True, upload_to=catalog.models.song_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac', 'm4a', 'ogg'])])),
                ('instrumental_file', models.FileField(blank=True, null=True, upload_to=catalog.models.song_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac', 'm4a', 'ogg'])])),
                ('lyrics_srt_file', models.FileField(blank=True, null=True, upload_to=catalog.models.song_upload_path, validators=[django.core.validators.FileExtensionValidator(['srt'])])),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration of the playable karaoke track.', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether non-admin users may browse and add this song.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['artist', 'title'],
            },
        ),
    ]
