# Generated by Django 5.2.17 on 2026-09-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='catalog_son_title_a8fc69_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='catalog_son_artist_89cdfb_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['processing_status'], name='catalog_son_process_7cad19_idx'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_song_title_per_artist'),
        ),
    ]
